const GET_ALL_TASKS = 'GET_ALL_TASKS'
const GET_NOT_COMPLETED_TASKS = 'GET_NOT_COMPLETED_TASKS'
const ASSIGN_TASK = 'ASSIGN_TASK'
const UNASSIGN_TASK = 'UNASSIGN_TASK'
const ADD_TASK = 'ADD_TASK'
const UPDATE_TASK = 'UPDATE_TASK'
const COMPLETE_TASK = 'COMPLETE_TASK'
const CANCEL_TASK = 'CANCEL_TASK'

const GET_ALL_ROLES = 'GET_ALL_ROLES'

const GET_ALL_USERS = 'GET_ALL_USERS'
const ADD_USER = 'ADD_USER'

const LOG_IN = 'LOG_IN'
const LOG_OUT = 'LOG_OUT'
const UNAUTHORIZED = 'UNAUTHORIZED'


export {
    GET_ALL_TASKS,
    GET_NOT_COMPLETED_TASKS,
    ASSIGN_TASK,
    LOG_IN,
    LOG_OUT,
    UNAUTHORIZED,
    UNASSIGN_TASK,
    ADD_TASK,
    UPDATE_TASK,
    COMPLETE_TASK,
    CANCEL_TASK,
    GET_ALL_ROLES,
    GET_ALL_USERS,
    ADD_USER
}
