const GET_ALL_TASKS = 'GET_ALL_TASKS'
const GET_NOT_COMPLETED_TASKS = 'GET_NOT_COMPLETED_TASKS'
const ASSIGN_TASK = 'ASSIGN_TASK'
const UNASSIGN_TASK = 'UNASSIGN_TASK'
const ADD_TASK = 'ADD_TASK'

const LOG_IN = 'LOG_IN'
const LOG_OUT = 'LOG_OUT'
const UNAUTHORIZED = 'UNAUTHORIZED'


export {
    GET_ALL_TASKS,
    GET_NOT_COMPLETED_TASKS,
    ASSIGN_TASK,
    LOG_IN,
    LOG_OUT,
    UNAUTHORIZED,
    UNASSIGN_TASK,
    ADD_TASK
}
